### ISSUE TITLE
use hyphens to decompose words

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lucene-sa#2]
Some input projects use hyphens to separate compounds of a word when the sandhi allows the placement of such an hyphen. Example: `mahārājādhirāja-śrī-candragupta-putrasya`. In this case, the word segmenter should take the hyphens into account and always consider them as compound boundaries. Because hyphens are not present in some sandhis, the analyzer should continue to compute boundaries based on other criteria.

**Comment by drupchen** [comment]
This touches the more general theme of sanskrit compounds. 
I would love to have an informed discussion about it.

The researches I have conducted about compounds led me to the conclusion that we anyhow will want to break them down into discreet words, then lemmatize them. So the fact hyphens are considered non-SLP forces the segmenter to stop the current token at the right place, thus improving the segmentation that our current Maximal-Matching approach gives.

My rough understanding of how compounds function is that they are simply un-sandhied words concatenated into a single lexical entity.

Taken as a whole, the very beginning of the compound (the beginning of the first word) could be modified by a sandhi and its very end (the end of the last word) could be modified by inflection and sandhi. 

The special treatment of compounds does not lie in the inflection or sandhi rules (correct me if I am wrong), but in what rules are applied given the morphological features of the words composing it.

If I am right, that means that having a Trie containing all possible combinations of both sandhi and inflection ensures we will ALWAYS have the right lemma as output of `SkrtWordTokenizer` to index.

As for now, I don't really see a user-case where we want to allow for queries that do not split up compounds, but that wouldn't really be a problem since we cover all sandhis and inflections.
